version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "convert-data-into-parquet"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ol1k76jcwcya"
s3_prefix = "convert-data-into-parquet"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
